spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: https://event-service-xwjwz3lfdq-ez.a.run.app
          predicates:
            - Path=/api/event/**
          filters:
            - JWTAuthenticationFilter

        - id: user-service
          uri: https://user-service-xwjwz3lfdq-ez.a.run.app
          predicates:
            - Path=/api/user/**


        - id: search-service
          uri: https://search-service-xwjwz3lfdq-ez.a.run.app
          predicates:
            - Path=/api/search/**
          filters:
            - JWTAuthenticationFilter

        - id: comment-service
          uri: https://comment-service-xwjwz3lfdq-ez.a.run.app
          predicates:
            - Path=/api/comment/**
          filters:
            - JWTAuthenticationFilter

        - id: discovery-server
          uri: https://discovery-service-xwjwz3lfdq-ez.a.run.app
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: https://discovery-service-xwjwz3lfdq-ez.a.run.app
          predicates:
            - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      #defaultZone: http://host.docker.internal:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: https://discovery-service-xwjwz3lfdq-ez.a.run.app/eureka/
app:
  #eureka-server: host.docker.internal
  #eureka-server: localhost
  eureka-server: discovery-service-xwjwz3lfdq-ez.a.run.app

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
